[Appearance]
style=Fusion
custom_palette=true
icon_theme={{icon-theme}}
color_scheme_path={{output-dir}}/qtct-colors.conf

[Fonts]
general="{{font-sans}},{{font-size-applications}},-1,5,50,0,0,0,0,0"
fixed="{{font-mono}},{{font-size-applications}},-1,5,50,0,0,0,0,0"
